<svg xmlns="http://www.w3.org/2000/svg" width="720" height="308"><foreignObject x="0" y="0" width="100%" height="100%"><div class="content" id="content" xmlns="http://www.w3.org/1999/xhtml" style="align-items: center; background-image: linear-gradient(to right, rgb(226, 226, 226), rgb(201, 214, 255)); color: rgb(230, 237, 243); display: flex; font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 13px; inline-size: 659.812px; justify-content: center; padding-block: 30px; padding: 30px; padding-inline: 30px; scrollbar-color: rgba(139, 148, 158, 0.2) rgb(13, 17, 23); unicode-bidi: isolate; width: 659.812px; -webkit-locale: &quot;en&quot;;">
      <div class="container bounce" id="container" style="animation-duration: 0.3s; animation-name: bounceF; animation-timing-function: cubic-bezier(0.28, 0.84, 0.42, 1); border-radius: 5px; border-end-end-radius: 5px; border-end-start-radius: 5px; border-start-end-radius: 5px; border-start-start-radius: 5px; box-shadow: rgba(0, 0, 0, 0.3) 0px 20px 60px 0px; display: flex; min-inline-size: 100px; min-width: 100px; overflow: hidden; transition-duration: 0.2s; transition-property: opacity; unicode-bidi: isolate;">
        <div style="unicode-bidi: isolate;">
          <div class="title" style="align-items: center; background-color: rgb(13, 17, 23); block-size: 35px; border-start-end-radius: 5px; border-start-start-radius: 5px; border-top-left-radius: 5px; border-top-right-radius: 5px; cursor: default; display: flex; height: 35px; padding-block: 3px; padding: 3px 18px; padding-inline: 18px; unicode-bidi: isolate;">
            <div class="dot dotA" style="background-color: rgb(255, 95, 85); block-size: 10px; border-radius: 50%; border-end-end-radius: 50%; border-end-start-radius: 50%; border-start-end-radius: 50%; border-start-start-radius: 50%; height: 10px; inline-size: 10px; margin-inline-end: 5px; margin-right: 5px; unicode-bidi: isolate; width: 10px;"></div>
            <div class="dot dotB" style="background-color: rgb(255, 189, 45); block-size: 10px; border-radius: 50%; border-end-end-radius: 50%; border-end-start-radius: 50%; border-start-end-radius: 50%; border-start-start-radius: 50%; height: 10px; inline-size: 10px; margin-inline-end: 5px; margin-right: 5px; unicode-bidi: isolate; width: 10px;"></div>
            <div class="dot dotC" style="background-color: rgb(37, 201, 63); block-size: 10px; border-radius: 50%; border-end-end-radius: 50%; border-end-start-radius: 50%; border-start-end-radius: 50%; border-start-start-radius: 50%; height: 10px; inline-size: 10px; margin-inline-end: 5px; margin-right: 5px; unicode-bidi: isolate; width: 10px;"></div>
            <div id="title" class="text" style="margin-inline-start: 10px; margin-left: 10px; unicode-bidi: isolate;">NavBar.jsx</div>
          </div>
          <div class="wrapper" style="background-color: rgb(13, 17, 23); display: flex; min-block-size: 150px; min-height: 150px; min-inline-size: 250px; min-width: 250px; padding-block: 10px; padding: 10px 18px; padding-inline: 18px; unicode-bidi: isolate;">
            <div id="lines" style="display: flex; flex-direction: column; margin-inline-end: 15px; margin-right: 15px; padding-block-end: 5px; padding-bottom: 5px; padding-inline-end: 5px; padding-right: 5px; unicode-bidi: isolate;"><span style="line-height: 24px; color: rgb(110, 118, 129); cursor: default; font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px;">34</span><span style="line-height: 24px; color: rgb(110, 118, 129); cursor: default; font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px;">35</span><span style="line-height: 24px; color: rgb(110, 118, 129); cursor: default; font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px;">36</span><span style="line-height: 24px; color: rgb(110, 118, 129); cursor: default; font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px;">37</span><span style="line-height: 24px; color: rgb(110, 118, 129); cursor: default; font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px;">38</span><span style="line-height: 24px; color: rgb(110, 118, 129); cursor: default; font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px;">39</span></div>
            <div id="output" style="unicode-bidi: isolate;"><div id="code" style="display: block; unicode-bidi: isolate;">

<!--StartFragment--><div style="background-color: rgb(13, 17, 23); font-family: Consolas, &quot;Courier New&quot;, monospace; font-size: 18px; line-height: 24px; white-space: pre; display: block; unicode-bidi: isolate;"><div style="display: block; unicode-bidi: isolate;"><span style="">  &lt;</span><span style="color: #7ee787;">ul</span><span style=""> </span><span style="color: #79c0ff;">className</span><span style="color: #ff7b72;">=</span><span style="color: #a5d6ff;">"flex"</span><span style="">&gt;</span></div><div style="display: block; unicode-bidi: isolate;"><span style="">        </span><span style="color: #ff7b72;">{</span></div><div style="display: block; unicode-bidi: isolate;"><span style="">            </span><span style="color: #79c0ff;">navigationData</span><span style="">.</span><span style="color: #d2a8ff;">map</span><span style="">(</span><span style="color: #ffa657;">rout</span><span style="color: #ff7b72;">=&gt;</span><span style="">&lt;</span><span style="color: #7ee787;">li</span><span style=""> </span><span style="color: #79c0ff;">className</span><span style="color: #ff7b72;">=</span><span style="color: #a5d6ff;">'mr-10'</span><span style="">&gt;</span></div><div style="display: block; unicode-bidi: isolate;"><span style="">                &lt;</span><span style="color: #7ee787;">a</span><span style=""> </span><span style="color: #79c0ff;">href</span><span style="color: #ff7b72;">={</span><span style="color: #ffa657;">rout</span><span style="">.</span><span style="">url</span><span style="color: #ff7b72;">}</span><span style="">&gt;</span><span style="color: #ff7b72;">{</span><span style="color: #ffa657;">rout</span><span style="">.</span><span style="">name</span><span style="color: #ff7b72;">}</span><span style="">&lt;/</span><span style="color: #7ee787;">a</span><span style="">&gt;&lt;/</span><span style="color: #7ee787;">li</span><span style="">&gt;</span><span style="">)</span></div><div style="display: block; unicode-bidi: isolate;"><span style="">        </span><span style="color: #ff7b72;">}</span></div><div style="display: block; unicode-bidi: isolate;"><span style="">      &lt;/</span><span style="color: #7ee787;">ul</span><span style="">&gt;</span></div></div><!--EndFragment-->

</div></div>
          </div>
          <div class="footer" id="footer" style="display: flex; background-color: rgb(13, 17, 23); border-bottom-left-radius: 5px; border-bottom-right-radius: 5px; border-end-end-radius: 5px; border-end-start-radius: 5px; justify-content: center; padding-block: 8px 12px; padding: 8px 8px 12px; padding-inline: 8px; unicode-bidi: isolate;">Snipped</div>
        </div>
      </div>  
    <style></style></div></foreignObject></svg>